### ISSUE TITLE
Native support for split weeks

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/did#232]
## Introduction
We've had a discussion in https://github.com/Puzzlepart/did365/issues/147 on how to handle split weeks. E.g. week 14 this year which is split between March and April. Right now this is not supported natively, and requires a workaround mentioned in https://github.com/Puzzlepart/did365/issues/147. [An issue for a informational message](https://github.com/Puzzlepart/did365/issues/231) has been created.

## The current situation
Right now the timesheet data are retrieved from the `graphql` backend at `/graphql`. A query and some variables are sent to this endpoint with method `POST` (See [Introduction to GraphQL](https://graphql.org/learn/)).

In type `EventDate` in the [GraphQL schema](https://github.com/Puzzlepart/did365/blob/dev/middleware/graphql/schema.graphql) you can see the format of the current response for the `timesheet` endpoint/resolver:

```graphql
type EventData {
 events: [Event!]!
 matchedEvents: [Event!]!
 totalDuration: Float!
 matchedDuration: Float!
 confirmedDuration: Float!
}
```

The endpoint takes three variables `startDateTime: String!`, `endDateTime: String!` and `dateFormat: String!` as you can see in the `Query` in the bottom the [GraphQL schema](https://github.com/Puzzlepart/did365/blob/dev/middleware/graphql/schema.graphql):

```graphql
type Query {
	customers: [Customer!]!
	projects(customerKey: String, sortBy: String): [Project!]!
	timesheet(startDateTime: String!, endDateTime: String!, dateFormat: String!): EventData!
	confirmedTimeEntries(projectId: String, resourceId: String, weekNumber: Int, yearNumber: Int, currentUser: Boolean, 	dateFormat: String): ConfirmedTimeEntries
	weeks: [Week!]!
	users: [User!]!
	currentUser: User!
	outlookCategories: [OutlookCategory!]!
}
```

In the resolver we first check if there's any confirmed events in the Azure table `ConfirmedTimeEntries`. 
* If there is, we return those
* If it's empty for the specified period, we send `startDateTime` and `endDateTime` in ISO format to the `Microsoft Graph` endpoint `/me/calendarView` and return these events

## Native support for split weeks
To support split week we'll need to introduce a `period` concept in the backend, and the frontend needs to "answer to this" new format.

In the backend we'll still receive the same parameters `startDateTime: String!`, `endDateTime: String!` and `dateFormat: String!`, but we have to check if it's a split week before we fetch any data.

- If it's a split week we'll need to fetch data for the two different parts/period independently
- If it's a normal week we'll just retrieve the data as before
 
We then need to return the data to the client in a different format. I suggest the `timesheet` endpoint returns an array of `type EventData` or `type TimesheetPeriod` (the naming is not the most important, but it's nice to have some proper naming). It should return an `id` for the period which could be a combination `weekNumber`, `monthNumber` and `yearNumber`, a `name` whih would be the month name or `Period n`, and the entries either from the `Microsoft Graph` or from the `ConfirmedTimeEntries` table.

The backend would render the periods as `PivotItem` components under the exisiting tabs and you would be able to confirm and unconfirm the entries/hours independently. 

![image](https://user-images.githubusercontent.com/7606007/78155794-34273300-743e-11ea-887b-b1e129c5fb66.png)

We would also have a tab `All week` that shows both parts. This would be the only visible tab if the week is not split. 

## Tasks
- [x] Change text for `Confirm week` and `Unconfirm week` to e.g. more generic `Confirm hours` and `Unconfirm hours`
- [x] Create function that checks if the week or period is split between months/years
- [x] Graphql endpoint `timesheet` should return an array of periods or parts. These objects should contain at least an `id`, `name` and `entries`.
- [x] Update [GraphQL schema](https://github.com/Puzzlepart/did365/blob/dev/middleware/graphql/schema.graphql)
- [x] Show only days in selected period in Summary view
- [x] Decide names for period tab headers
- [x] Visualise split week in week picker command bar ("week 14.1, week 14.2")
- [x] Import i18n/index instead of i18next so we can do `resource('key')` instead of `i18n.t('key)`
- [x] Move event matching from `timesheet.js` to `timesheet.matching.js` for readability
- [x] Investigate if we need to have customer on both the event and the event's matched project (Ref https://github.com/Puzzlepart/did365/pull/237/files#diff-1b1678f8369b7f4bb3108fb93e8d17feR164  https://github.com/Puzzlepart/did365/pull/237/files#diff-1b1678f8369b7f4bb3108fb93e8d17feR179)
