### ISSUE TITLE
Using react-router for navigation

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/did#297]
- [x] I have searched for existing issues to avoid creating duplicates

### TLDR
We should use react-router for navigation.

### Description
Using react-router for controlling React components. Express will handle `/graphql` and `/auth` routes and will send rest to the client for React to do the routing.

### PR
#296 

### TODO
- [x] Ensure all routes work 100%
- [x] Look at how to pass context to React from Express
