### ISSUE TITLE
[i18n] Norwegian translation

### ISSUE THREAD

**Issue by damsleth** [Puzzlepart/did#306]
- [X] I have searched for existing issues to avoid creating duplicates

### TLDR
I want a norwegian translation of DID365.

### Description
We've implemented i18n, with `en` as default language.
We should have a norwegian (`nb_NO`) translation as well.

# Todos

- [x] The resource files should contain the name of the language, so we don’t need to keep it in the code 🚀 
- [X] Measurements, specifically hours shorthand ("t" vs "h")
- [x] Calendar
