### ISSUE TITLE
Language setting in user settings

### ISSUE THREAD

**Issue by damsleth** [Puzzlepart/did#309]
- [X] I have searched for existing issues to avoid creating duplicates

### TLDR
I would like to change my DID365 display language

### Description
I want a settings context menu where I can change my display language, preferably a right hand panel like the notifications panel

### TODOS

- [ ] Mutation in User resolver for updating user
- [ ] Update user member in StorageService (if it doesn't already)
- [ ] On setting change, send mutation updateUser to graphql
