### ISSUE TITLE
Fix rendering of weblink on customer details and project details

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/did#319]
- [x] I have searched for existing issues to avoid creating duplicates

### What  ###
Should render `ExternalSystemURL` and `WebLink` as buttons Not quite sure how we render it. What we should as `text`. Need some ideas.

![image](https://user-images.githubusercontent.com/7606007/81053244-0ca40a00-8ec5-11ea-9285-ed4c9cbc5fd3.png)

### Browser ####
All

### Todo ###
- [ ] Render a button for `ExternalSystemURL` for CustomerDetails
- [ ] Render a button for `WebLink` for CustomerDetails
- [ ] Render a button for `ExternalSystemURL` for ProjectDetails
- [ ] Render a button for `WebLink` for ProjectDetails
