### ISSUE TITLE
v0.10.0 migration checklist

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/did#854]
## v0.10.0 migration checklist

**Production data is currently stored in storage account [did85de37e8af91]([did85de37e8af91 - Microsoft Azure](https://portal.azure.com/#@puzzlepart.com/resource/subscriptions/b5e5e285-a57a-4593-a2ef-221dc037ac9f/resourceGroups/pzl-did/providers/Microsoft.Storage/storageAccounts/did85de37e8af91/storageexplorer))**

**Development data is currently stored in Azure Cosmos DB account [did-dev-puzzlepart-85de37e8af91]([did-dev-puzzlepart-85de37e8af91 - Microsoft Azure](https://portal.azure.com/#@puzzlepart.com/resource/subscriptions/b5e5e285-a57a-4593-a2ef-221dc037ac9f/resourceGroups/pzl-did-dev/providers/Microsoft.DocumentDb/databaseAccounts/did-dev-puzzlepart-85de37e8af91/dataExplorer))**
- [x] Backup application settings for did prod (for rollback) 
- [x] Export time entries to `Cosmos DB`(mongodb)
  - [x] Find a good way to convert it to [correct format]([did/data_model.dmm at dev · Puzzlepart/did (github.com)](https://github.com/Puzzlepart/did/blob/dev/data_model.dmm))
- [x] Export confrmed periods to `Cosmos DB`(mongodb) (see [data model (open with Moon Modeler)]([did/data_model.dmm at dev · Puzzlepart/did (github.com)](https://github.com/Puzzlepart/did/blob/dev/data_model.dmm))
- [x] Export forecasted periods to `Cosmos DB`(mongodb)
- [x] Export users to `Cosmos DB`(mongodb)
- [x] Export customers to `Cosmos DB`(mongodb)
- [x] Export projects to `Cosmos DB`(mongodb)
- [x] Export labels to `Cosmos DB`(mongodb)
- [x] Export roles to  `Cosmos DB`(mongodb)
- [x] Create `Cosmos DB` account with mongodb as API
- [x] Create `main` database
  - [x] Set up `subscriptions` collection
  - [x] Set up `api_tokens` collection
- [x] Create `Puzzlepart`database
  - [x] Set up `users` collection with [indexing policy](https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-indexing)
  - [x] Set up `time_entries` collection with [indexing policy](https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-indexing)
  - [x] Set up `forecasted_time_entries` collection with [indexing policy](https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-indexing)
  - [x] Set up `roles` collection with [indexing policy](https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-indexing)
  - [x] Set up `projects` collection with [indexing policy](https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-indexing)
  - [x] Set up `customers`collection with [indexing policy](https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-indexing)
  - [x] Set up `confirmed_periods`collection with [indexing policy](https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-indexing)
  - [x] Set up `forecasted_periods`collection with [indexing policy](https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-indexing)
  - [x] Set up `labels`collection with [indexing policy](https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-indexing)
  - [x] https://github.com/Puzzlepart/did/issues/861
  - [x] Setup Redis (#812)
